name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: |
          echo "No tests yet"
          # nếu có test thì chạy: npm test

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/todo-nodejs
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  simple-deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: 🎉 Deploy hoàn thành
        run: |
          echo "✅ Docker image đã được build và push thành công!"
          echo "🐳 Image có thể tải về bằng lệnh:"
          echo "   docker pull ${{ secrets.DOCKER_USERNAME }}/todo-nodejs:latest"
          echo ""
          echo "🚀 Để chạy ứng dụng trên máy local:"
          echo "   docker run -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/todo-nodejs:latest"
          echo ""
          echo "🌐 Các platform deploy dễ dàng khác:"
          echo "   - Heroku (free tier)"
          echo "   - Railway.app"
          echo "   - Render.com"
          echo "   - Vercel (cho Node.js)"
          echo "   - DigitalOcean App Platform"

  